#!/bin/bash

# Layer 4: final merge over Layer 3 era outputs.

export L3_ROOT="${L3_ROOT:-/lustre/projects/polyullm/lipengxiang_tmp/fineweb_012_dedup_l3_era}"
export L4_ROOT="${L4_ROOT:-/lustre/projects/polyullm/lipengxiang_tmp/fineweb_012_dedup_l4_global}"

export INPUT_PATH="${INPUT_PATH:-${L3_ROOT}/era_*/result}"
export OUTPUT_PATH="${OUTPUT_PATH:-${L4_ROOT}/global}"
export TEXT_KEY="${TEXT_KEY:-text}"
export SCORE_KEY="${SCORE_KEY:-stage3_score}"
export WEIGHT_KEY="${WEIGHT_KEY:-duplicate_count}"

export THRESHOLD="${THRESHOLD:-0.85}"
export NGRAM_SIZE="${NGRAM_SIZE:-5}"
export MIN_LENGTH="${MIN_LENGTH:-10}"
export NUM_PERM="${NUM_PERM:-128}"
export B="${B:-8}"
export R="${R:-16}"

export SQL_SHUFFLE_PARTITIONS="${SQL_SHUFFLE_PARTITIONS:-32768}"
export MINHASH_INPUT_PARTITIONS="${MINHASH_INPUT_PARTITIONS:-32768}"
export WCC_PARALLELISM="${WCC_PARALLELISM:-8192}"
export SKIP_EXACT_DEDUP="${SKIP_EXACT_DEDUP:-true}"

export DRIVER_MEMORY="${DRIVER_MEMORY:-128G}"
export DRIVER_CORES="${DRIVER_CORES:-8}"
export EXECUTOR_MEMORY="${EXECUTOR_MEMORY:-300G}"
export EXECUTOR_MEMORY_OVERHEAD="${EXECUTOR_MEMORY_OVERHEAD:-256G}"
export SPARK_OFFHEAP_SIZE="${SPARK_OFFHEAP_SIZE:-48g}"

export SPARK_UI_RETAINED_TASKS="${SPARK_UI_RETAINED_TASKS:-1000}"
export SPARK_UI_RETAINED_STAGES="${SPARK_UI_RETAINED_STAGES:-50}"
export SPARK_UI_RETAINED_JOBS="${SPARK_UI_RETAINED_JOBS:-50}"
export SPARK_SQL_UI_RETAINED_EXECUTIONS="${SPARK_SQL_UI_RETAINED_EXECUTIONS:-20}"
export SPARK_UI_TIMELINE_TASKS_MAXIMUM="${SPARK_UI_TIMELINE_TASKS_MAXIMUM:-1000}"
export SPARK_EXECUTOR_HEARTBEAT_INTERVAL="${SPARK_EXECUTOR_HEARTBEAT_INTERVAL:-60s}"
export SPARK_NETWORK_TIMEOUT="${SPARK_NETWORK_TIMEOUT:-600s}"
